services:
  mqtt-log-collector:
    build:
      context: ./collector
    container_name: mqtt-log-collector
    env_file:
      - .env
    environment:
      LOG_ROOT: /logs
      USERS_FILE: /users/users.txt
      TIMEZONE: America/Sao_Paulo
    volumes:
      - ./logs:/logs
      - ./users:/users:ro
    restart: unless-stopped
